# Generated by Django 3.2.5 on 2021-07-24 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.URLField()),
                ('email_host_port', models.IntegerField(default=587)),
                ('email_address', models.EmailField(max_length=254)),
                ('email_address_password', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='UserContributionConf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('next_billing_date', models.DateField()),
                ('bill_period', models.CharField(choices=[('once', 'Billed Once'), ('monthly', 'Billed Monthly'), ('annual', 'Billed Annual')], default='once', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('billed_on', models.DateField()),
                ('donation_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
