# Generated by Django 3.2.5 on 2021-07-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesaPalCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesapal_consumer_key', models.CharField(max_length=256)),
                ('pesapal_consumer_secret', models.CharField(max_length=256)),
                ('debug', models.BooleanField(default=True)),
            ],
        ),
    ]
