# Generated by Django 3.2.5 on 2021-07-25 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0002_pesapalcredentials'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pesapalcredentials',
            options={'verbose_name_plural': 'PesaPal Integration Credentials'},
        ),
        migrations.CreateModel(
            name='PesaPalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=256)),
                ('tracking_id', models.CharField(max_length=256)),
                ('amount', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
