# Generated by Django 3.2.5 on 2021-07-25 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0003_auto_20210725_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesapalorder',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usercontributionconf',
            name='next_billing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
