# Generated by Django 3.2.5 on 2021-07-25 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_pesapalorder_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pesapalorder',
            options={},
        ),
    ]
