# Generated by Django 3.2.5 on 2021-07-26 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_pesapalorder_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pesapalorder',
            options={'verbose_name_plural': 'Pesapal Donation Orders'},
        ),
        migrations.AddField(
            model_name='usercontributionconf',
            name='day',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercontributionconf',
            name='month',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
